# This is a basic workflow to help you get started with Actions

name: Full Test Suite on Windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    SCONS_CACHE_MSVC_CONFIG: 1

jobs:
  runtest-win32:
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        optenv: [false, true]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip
          python -m pip install --progress-bar off -r requirements-dev.txt

      - name: Install Chocolatey packages
        run: |
          choco install --yes --no-progress dmd winflexbison3

      - name: runtest (optenv=${{ matrix.optenv }})
        if: ${{ !matrix.optenv }}
        run: |
          python runtest.py --all --exclude-list=windows_ci_skip.txt --time --jobs=4

      - name: runtest (optenv=${{ matrix.optenv }})
        if: ${{ matrix.optenv }}
        run: |
          python runtest.py --all --exclude-list=windows_ci_skip.txt --time --jobs=4
        env:
          POWERSHELL_TELEMETRY_OPTOUT: 1
          PSDisableModuleAnalysisCacheCleanup: 1
          VCPKG_DISABLE_METRICS: 1
          VSCMD_SKIP_SENDTELEMETRY: 1

      - name: Archive Failed tests
        uses: actions/upload-artifact@v4
        with:
          name: windows-failed-tests
          path: |
            failed_tests.log
